version: "2.1"

volumes:
  nextcloud:
  mariadb:
  duplicati:

services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - nextcloud:/var/www/html
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "*.balena-devices.com"
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      REDIS_HOST: redis
    depends_on:
      - mariadb
      - redis
  
  # https://hub.docker.com/_/nextcloud/
  cron:
    image: nextcloud:stable-fpm-alpine
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis

  # https://hub.docker.com/_/nginx/
  nginx:
    build: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    build: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
  
  # https://hub.docker.com/_/mariadb/
  mysqldump:
    image: mariadb
    command:
      - "/bin/bash"
      - "-c"
      - "while : ; sleep 1h ; do mysqldump -h mariadb -u root -p${MYSQL_ROOT_PASSWORD} -d zm > /var/lib/mysql/mysqldump.sql ; done"
    volumes:
      - mariadb:/var/lib/mysql
    depends_on:
      - mariadb

  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:arm64v8-latest
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - nextcloud:/source/nextcloud
      - mariadb:/source/mariadb
