version: "2.1"

volumes:
  nextcloud:
  custom_apps:
  config:
  themes:
  mariadb:
  traefik:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - "nextcloud:/var/www/html"
      - "custom_apps:/var/www/html/custom_apps"
      - "config:/var/www/html/config"
      - "themes:/var/www/html/themes"
    environment:
      - "NEXTCLOUD_DATA_DIR=/data"
      - "NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.${ROOT_DOMAIN},*.balena-devices.com"
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"
      - "MYSQL_HOST=mariadb"
    labels:
      traefik.enable: true
      traefik.docker.network: nextcloud
      traefik.backend: nextcloud
      traefik.protocol: http
      traefik.port: 80
      traefik.frontend.rule: Host:nextcloud.${ROOT_DOMAIN}
      traefik.frontend.entryPoint: http
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.priority: 1
      traefik.frontend.passHostHeader: true
      # traefik.frontend.auth.basic.users: ${HTPASSWD}

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10-bionic
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=nextcloud"

  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik:v1.7.13-alpine
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "traefik:/etc/traefik"
    command: 
      - "--debug=false"
      - "--logLevel=DEBUG"
      - "--api=true"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--acme.storage=/etc/traefik/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge=true"
      - "--acme.dnsChallenge.provider=cloudflare"
      # - "--acme.dnsChallenge.delayBeforeCheck=60"
      - "--acme.onHostRule=true"
      # - "--acme.email=${CF_API_EMAIL}"
      - "--acme.acmeLogging=true"
      # - "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory" # staging server
      - "--docker"
      # - "--docker.domain=${ROOT_DOMAIN}"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.endpoint=unix:///var/run/balena.sock"
      - "--retry"
    labels:
      io.balena.features.balena-socket: true
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.backend: traefik
      traefik.protocol: http
      traefik.port: 8080
      traefik.frontend.rule: Host:traefik.${ROOT_DOMAIN}
      traefik.frontend.entryPoint: http
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.priority: 1
      traefik.frontend.passHostHeader: true
      traefik.frontend.auth.basic.users: ${HTPASSWD}
