version: "2.1"

volumes:
  nextcloud:
  mariadb:
  traefik:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: .
    privileged: true
    ports:
      - "80:80/tcp"
    volumes:
      - "nextcloud:/var/www/html"
    environment:
      TRUSTED_PROXIES: traefik localhost
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.middlewares: secureheaders, cardcaldav
      traefik.http.middlewares.cardcaldav.replacepathregex.regex: ^/.well-known/(card|cal)dav
      traefik.http.middlewares.cardcaldav.replacepathregex.replacement: /remote.php/dav/
      traefik.http.middlewares.secureheaders.headers.stsSeconds: 15552000
      traefik.http.middlewares.secureheaders.headers.framedeny: true
      traefik.http.middlewares.secureheaders.headers.sslForceHost: true
      traefik.http.middlewares.secureheaders.headers.sslRedirect: true
      traefik.http.middlewares.secureheaders.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.secureheaders.headers.browserXssFilter: true
      traefik.http.middlewares.secureheaders.headers.contentTypeNosniff: true
      traefik.http.middlewares.secureheaders.headers.forceSTSHeader: true
      traefik.http.middlewares.secureheaders.headers.stsPreload: true
      traefik.http.middlewares.secureheaders.headers.customResponseHeaders.X-Robots-Tag: none
      traefik.http.middlewares.secureheaders.headers.customFrameOptionsValue: SAMEORIGIN

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10
    command: --max-allowed-packet=67108864
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik:2.2
    ports:
      # - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "traefik:/etc/traefik"
    environment:
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      # TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: :80
      # TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: :443
      TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: tlschallenge
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/balena.sock
      TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_TLSCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_STORAGE: /etc/traefik/acme.json
      # TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      io.balena.features.balena-socket: true
