version: "2.1"

volumes:
  nextcloud:
  mariadb:
  duplicati:

services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    command:
      - "/bin/sh"
      - "-c"
      - "/mount.sh && php-fpm"
    volumes:
      - nextcloud:/var/www/html
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "*.balena-devices.com"
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      REDIS_HOST: redis
    depends_on:
      - mariadb
      - redis
  
  # https://hub.docker.com/_/nextcloud/
  cron:
    build: nextcloud
    privileged: true
    command:
      - "/bin/sh"
      - "-c"
      - "/mount.sh && /cron.sh"
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
      - redis

  # https://hub.docker.com/_/nginx/
  nginx:
    build: nginx
    ports:
      - 80:80/tcp
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    build: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
  
  # https://hub.docker.com/_/mariadb/
  mysqldump:
    build: mariadb
    command:
      - "/bin/bash"
      - "-c"
      - "while : ; sleep 1h ; do mysqldump -h mariadb -u root -p${MYSQL_ROOT_PASSWORD} -d zm > /var/lib/mysql/mysqldump.sql ; done"
    volumes:
      - mariadb:/var/lib/mysql
    depends_on:
      - mariadb

  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:arm64v8-latest
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - nextcloud:/source/nextcloud
      - mariadb:/source/mariadb

  # optional sshd service for transferring data in/out
  # or performing external backups via rsync & ssh
  sshd:
    build: nextcloud
    privileged: true
    command:
      - "/bin/sh"
      - "-c"
      - "/mount.sh && /sshd.sh"
    volumes:
      - nextcloud:/var/www/html
      - mariadb:/var/lib/mysql
