version: "2.1"

volumes:
  nextcloud:
  mariadb:
  traefik:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - "nextcloud:/var/www/html"
    environment:
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_UPDATE: 1
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    labels:
      traefik.enable: true
      traefik.http.routers.web.entrypoints: web
      traefik.http.routers.web.middlewares: redirect
      traefik.http.routers.websecure.entrypoints: websecure
      traefik.http.routers.websecure.tls.certresolver: mydnschallenge
      traefik.http.middlewares.redirect.redirectscheme.scheme: https
      customLabel: nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10.4.8-bionic
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik:2.0.0-rc4
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "traefik:/etc/traefik"
    environment:
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: :443
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/balena.sock
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DNSCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DNSCHALLENGE_PROVIDER: cloudflare
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_STORAGE: /etc/traefik/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_CASERVER: https://acme-v02.api.letsencrypt.org/directory
    labels:
      io.balena.features.balena-socket: true
