version: "2.1"

volumes:
  nextcloud:
  mariadb:
  nginx:
  traefik:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - "nextcloud:/var/www/html"
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: https
      traefik.http.routers.nextcloud.tls.certresolver: tlschallenge
      traefik.http.routers.nextcloud.middlewares: secureheaders, cardcaldav
      traefik.http.middlewares.cardcaldav.replacepathregex.regex: ^/.well-known/(card|cal)dav
      traefik.http.middlewares.cardcaldav.replacepathregex.replacement: /remote.php/dav/
      subdomain: nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  # https://hub.docker.com/_/nginx/
  nginx:
    build: ./nginx
    privileged: true
    volumes:
      - "nginx:/etc/nginx"
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.entrypoints: https
      traefik.http.routers.nginx.tls.certresolver: tlschallenge
      traefik.http.routers.nginx.middlewares: secureheaders, basicauth
      subdomain: nginx

  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "traefik:/etc/traefik"
    environment:
      TRAEFIK_LOG_LEVEL: INFO
      TRAEFIK_API: true
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: :443
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/balena.sock
      TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_TLSCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_STORAGE: /etc/traefik/acme.json
      # TRAEFIK_CERTIFICATESRESOLVERS_TLSCHALLENGE_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      io.balena.features.balena-socket: true
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.tls.certresolver: tlschallenge
      traefik.http.routers.traefik.middlewares: secureheaders, basicauth
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.http.entrypoints: http
      traefik.http.routers.http.rule: HostRegexp(`{catchall:.+}`)
      traefik.http.routers.http.middlewares: redirectscheme
      traefik.http.middlewares.redirectscheme.redirectscheme.scheme: https
      traefik.http.middlewares.basicauth.basicauth.usersfile: /etc/traefik/.htpasswd
      traefik.http.middlewares.secureheaders.headers.stsSeconds: 15552000
      traefik.http.middlewares.secureheaders.headers.framedeny: true
      traefik.http.middlewares.secureheaders.headers.sslForceHost: true
      traefik.http.middlewares.secureheaders.headers.sslRedirect: true
      traefik.http.middlewares.secureheaders.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.secureheaders.headers.browserXssFilter: true
      traefik.http.middlewares.secureheaders.headers.contentTypeNosniff: true
      traefik.http.middlewares.secureheaders.headers.forceSTSHeader: true
      traefik.http.middlewares.secureheaders.headers.stsPreload: true
      traefik.http.middlewares.secureheaders.headers.customResponseHeaders.X-Robots-Tag: none
      traefik.http.middlewares.secureheaders.headers.customFrameOptionsValue: SAMEORIGIN
      subdomain: traefik
