version: "2.1"

volumes:
  nextcloud:
  mariadb:
  duplicati:

services:
  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    entrypoint: "/bin/sh"
    command:
      - "-c"
      - "/mount.sh && /configure.sh && /entrypoint.sh php-fpm"
    volumes:
      - nextcloud:/var/www/html
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "*.balena-devices.com"
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: nextcloud
      TZ: America/Toronto
    depends_on:
      - mariadb
      - redis
  
  # https://hub.docker.com/_/nextcloud/
  cron:
    build: nextcloud
    privileged: true
    entrypoint: "/bin/sh"
    command:
      - "-c"
      - "/mount.sh && /cron.sh"
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
      - redis

  # https://hub.docker.com/_/nginx/
  nginx:
    build: nginx
    ports:
      - 80:80/tcp
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    build: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
  
  # https://hub.docker.com/_/mariadb/
  sqldump:
    build: mariadb
    command: "/sqldump.sh"
    environment:
      MYSQL_DATABASE: nextcloud
    volumes:
      - mariadb:/var/lib/mysql
    depends_on:
      - mariadb

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.0.8-alpine
    command: redis-server --requirepass nextcloud

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati:arm64v8-latest
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - nextcloud:/source/nextcloud
      - mariadb:/source/mariadb
