version: "2.1"

volumes:
  nextcloud:
  custom_apps:
  config:
  themes:
  mariadb:
  traefik:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    privileged: true
    volumes:
      - "nextcloud:/var/www/html"
      - "custom_apps:/var/www/html/custom_apps"
      - "config:/var/www/html/config"
      - "themes:/var/www/html/themes"
    environment:
      - "NEXTCLOUD_DATA_DIR=/data"
      - "MYSQL_HOST=mariadb"
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls.certresolver: mydnschallenge
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.http.services.nextcloud.loadbalancer.server.scheme: http
      my.service.subdomain: nextcloud

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10.4.7-bionic
    volumes:
      - "mariadb:/var/lib/mysql"

  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik:2.0.0-beta1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "traefik:/etc/traefik"
    environment:
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: :443
      TRAEFIK_PROVIDERS_DOCKER: true
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: unix:///var/run/balena.sock
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DNSCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_DNSCHALLENGE_PROVIDER: cloudflare
      TRAEFIK_CERTIFICATESRESOLVERS_MYDNSCHALLENGE_ACME_STORAGE: /etc/traefik/acme.json
    labels:
      io.balena.features.balena-socket: true
