version: '2.1'

volumes:
  nextcloud:
  custom_apps:
  config:
  themes:
  mariadb:

services:

  # https://hub.docker.com/_/nextcloud/
  nextcloud:
    build: nextcloud
    ports:
      - 80:80
    privileged: true
    volumes:
      - 'nextcloud:/var/www/html'
      - 'custom_apps:/var/www/html/custom_apps'
      - 'config:/var/www/html/config'
      - 'themes:/var/www/html/themes'
    environment:
      - 'NEXTCLOUD_DATA_DIR=/data'
      - 'NEXTCLOUD_TRUSTED_DOMAINS=*.balena-devices.com'
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'
      - 'MYSQL_HOST=mariadb'

  # https://hub.docker.com/_/mariadb/
  mariadb:
    image: mariadb:10-bionic
    volumes:
      - 'mariadb:/var/lib/mysql'
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=yes'
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'